export const EntityNames = {
  TasksTable: "TasksTable",
  UserTable: "UserTable",
  FilesTable: "FilesTable",
  FilesBucket: "FilesBucket",
  TodoUserPool: "TodoUserPool",
  TodoUserPoolClient: "TodoUserPoolClient",
  TodoAuthorizer: "TodoAuthorizer",
  TasksQueue: "TasksQueue",
  TasksDQL: "TasksDQL",
  TasksEventBus: "TasksEventBus",
  TimeService: "TimeService",
  TaskService: "TaskService",
  UserService: "UserService",
  TaskWorker: "TaskWorker",
  FileWorker: "FileWorker",
  TaskCreatedRule: "TaskCreatedRule",
  FileUploadRule: "FileUploadRule",
  TodoApi: "TodoApi",
  DefaultBus: "default",
} as const;
