export enum EntityNames {
  TasksTable = "TasksTable",
  UserTable = "UserTable",
  FilesTable = "FilesTable",
  TodoUserPool = "TodoUserPool",
  TodoUserPoolClient = "TodoUserPoolClient",
  TodoAuthorizer = "TodoAuthorizer",
  TasksQueue = "TasksQueue",
  TasksDQL = "TasksDQL",
  TasksEventBus = "TasksEventBus",
  TimeService = "TimeService",
  TaskService = "TaskService",
  TaskWorker = "TaskWorker",
  TaskCreatedRule = "TaskCreatedRule",
  TodoApi = "TodoApi",
}
