export const EntityNames = {
  TasksTable: "TasksTable",
  UserTable: "UserTable",
  FilesTable: "FilesTable",
  TodoUserPool: "TodoUserPool",
  TodoUserPoolClient: "TodoUserPoolClient",
  TodoAuthorizer: "TodoAuthorizer",
  TasksQueue: "TasksQueue",
  TasksDQL: "TasksDQL",
  TasksEventBus: "TasksEventBus",
  TimeService: "TimeService",
  TaskService: "TaskService",
  UserService: "UserService",
  TaskWorker: "TaskWorker",
  TaskCreatedRule: "TaskCreatedRule",
  TodoApi: "TodoApi",
} as const;
